const express = require("express");
const bodyParser = require('body-parser')
const app = express();
const mysql = require("mysql");
const cors = require("cors");
// const bcrypt = require('bcrypt');
const jwt = require("jsonwebtoken");
const { response } = require("express");
const jwtKey = 'f-t';
// const session = require("cookie-parder");
const cookieParser = require("cookie-parser");
const {verifyAccessToken} = require('./verifyToken')